### ISSUE TITLE
Docker image broken?

### ISSUE THREAD

**Issue by gadget1999** [sudoforge/docker-mumble-server#121]
I tried with the command in the instruction: 
docker run -d \
    -p 64738:64738/tcp \
    -p 64738:64738/udp \
    --name mumble-server-001 \
    sudoforge/mumble-server

But the container will exit shortly after. Following is the docker logs output. Tried this on multiple machines and got same output every time. Is it possible something is broken? Thanks

SUPERUSER_PASSWORD: **************************************
Failed to set initial capabilities
<W>2021-01-31 16:19:21.897 SSL: OpenSSL version is 'OpenSSL 1.0.2k  26 Jan 2017'
<W>2021-01-31 16:19:21.897 Initializing settings from /etc/murmur/murmur.ini (basepath /etc/murmur)
<W>2021-01-31 16:19:21.897 Binding to address 0.0.0.0
<W>2021-01-31 16:19:21.966 MetaParams: TLS cipher preference is "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:AES256-SHA:AES128-SHA"
<C>2021-01-31 16:19:21.967 Successfully switched to uid 100
<C>2021-01-31 16:19:21.967 Failed to set initial capabilities
<W>2021-01-31 16:19:21.980 ServerDB: Opened SQLite database /data/murmur.sqlite
<W>2021-01-31 16:19:21.980 ServerDB: Using SQLite's default rollback journal.
<W>2021-01-31 16:19:23.081 Performed initial PBKDF2 benchmark. Will use 8000 iterations as default
<W>2021-01-31 16:19:23.081 Generating new tables...
<F>2021-01-31 16:19:23.128 Superuser password set on server 1

**Comment by sudoforge** [comment]
Thank you for the report.

Reproduced. Investigating now. Something else I'll need to look into is why the CI test passed with whatever introduced this issue.

**Comment by sudoforge** [comment]
Okay, the issue here is that I erroneously removed a workaround for the issue described in mumble-voip/mumble#3911, in commit b7a0867ca935e0bda1057f6760df0551ccb33409.

More specifically, the issue is that I made an assumption about the 1.3.1 release; I assumed that it would contain the upstream fix for the upstream issue. I did not confirm this, and apparently, did not thoroughly test the process after updating it, instead relying on the paltry CI test to confirm that things were working. They weren't.

The reason this fails for you and not for me, in my normal usage of this image, is that you were spinning up a new container that didn't have a database, and you didn't provide a value for the `SUPERUSER_PASSWORD`. Because of those two conditions, we generate a password and call the binary with the `-supw` argument, which starts the server and sets the superuser passphrase, then exits. The code (in the entrypoint script) handling this can be seen below:

https://github.com/sudoforge/docker-mumble-server/blob/078c147b2a9a5b24955b7ef1d4b1d867b9b0dfe0/docker-entrypoint.sh#L89-L97

The underlying issue here is that the upstream codebase uses `qFatal` instead of `qInfo` to display the "Superuser password set on server"  message. This causes the above call to `exit 1` -- in other words, it causes the program to always exit as if a failure occurred, when in fact, one did not. This was indeed fixed in mumble-voip/mumble#3998, however, the way the team creates releases depends on them backporting fixes into the release tree. This was not done.

I opened an upstream issue to highlight this: mumble-voip/mumble#4728.

---

In the mean time, I have re-applied the fix I used for this previously, and tested it thoroughly (manually). You should now be able **to re-pull the latest image and be well on your way.**

Thanks again for highlighting this! It's actually been present since my removal of the appropriate workaround with the `1.3.1` release back in June 2020. Yikes!

**Comment by gadget1999** [comment]
It works perfectly now, thanks a lot for the quick response!
