### ISSUE TITLE
Your DMCA claim

### ISSUE THREAD

**Issue by Krzmbrzl** [sudoforge/docker-mumble-server#133]
Hi tthere,
Since I don't have any email or something like that, I figured abusing issues might be the best way to contact you.

I wanted to reach out to you to hear specifics as to why you renewed your DMCA claim on https://github.com/mumble-voip/mumble-docker after the repo has been rebased and the parts that where copied from your repo have been replaced. I honestly don't know what else you expected to happen.
Please let me know, so we can take the necessary actions to once and for all settle this.

To be clear: This is not about why you filed the initial DMCA. That I understood. What I don't understand is why you were not satisfied with the changes made after that.

**Comment by sudoforge** [comment]
@Krzmbrzl and I spoke on Matrix, and have come to an agreeable solution -- I will be applying the modifications that were made to my licensed work in sequence, with appropriate authorship attribution where feasible, in order to remediate the DMCA violation.

Having been the maintainer of the primary image used for `mumble-server` (formerly "Murmur") for the past 7 years, I am looking forward to working together now and in the future to ensure that the many users of the Mumble community are able to benefit from our combined development efforts.
