### ISSUE TITLE
Versioning options

### ISSUE THREAD

**Issue by sudoforge** [sudoforge/docker-mumble-server#27]
How should we version this repo? The most straightforward method would be retaining the same version number as the version of `murmur` installed with the package -- this would allow users to easily `docker pull bddenhartog/docker-murmur:<version>` and get an image with the appropriate version of murmur.

The other option is to version based on the issues and goals from within this repo directly. This would be more appropriate and would allow version numbers to support specific development targets, but may be more confusing to the end user (as we may quickly out-version the `mumble` project, and `vX` of this repo may only correspond to `vY` of the murmur project.

**Comment by bddenhartog** [comment]
Thoughts @SISheogorath?

**Comment by SISheogorath** [comment]
Mhm, it's difficult. As long as we don't break it the versioning like the `murmur` version would work.

If we break something it's a problem.

Lets take a realistic point of view: How many people actually using this container? I guess less than 50. So we want to take a road where more people can use it. This leads us to the problem that we need a working version. Right now a lot of stuff is working but not everything. What could break in future? As we already have the config in environment variables, the container itself, besides the database, is stateless and logging goes to stdout/stderr there is not much we can break for now. So lets take the original murmur version and add different builds, when we add a feature.

The docker compose stuff can be prefixed with `compose-` if we want to create a release so the docker build can be ignored. should be easy.

**Comment by bddenhartog** [comment]
I was thinking along the same lines; `latest` should always correspond to the latest stable version of murmur, so it makes sense that any tag in this repository (and on the image) corresponds to the appropriate version of murmur.

It's possible (although maybe not ideal) to change the commit that the tag points to. On the docker repository side of things, which would enable something like:

```text
$ docker pull bddenhartog/docker-murmur:1.2.17  # latest version of image based on murmur v1.2.17
> ... changes happen upstream, we add some new feature or bugfix ...
$ docker pull bddenhartog/docker-murmur:1.2.17 # latest version of image based on murmur v1.2.17
```

I think this is the best workflow from a user-centric perspective, but a horrible workflow from a development perspective, as now we have no way to convey that users *should* update their image -- e.g. `featureX added in v1.2.17` when the user has already pulled `v1.2.17` from the repo, without `featureX`.

How would you want to add the build number, and what should it be based on -- the travis build? the commit SHA? Something like:

```text
image:1.2.17-0064
image:1.2.17-670c69c3
image:1.2.17-stable (first build of 1.2.17? latest?)
```

I think the issue with using murmur's version, which I do not like, is there is no way for us to differentiate our versioning from theirs. We may add a whole bunch of project specific features for 1.2.17, for example, and sticking with semver and murmur's version there's no way to easily identify those.

**Comment by SISheogorath** [comment]
I'm more and more coming the conclusion that the "docker magic" stuff we do here "shouldn't matter". Yes, we can't release new versions like you would usually would do it, but in fact Docker handles the "build numbers" itself. So no need to add something like `-SHA1`. We can simply use the `murmur`. If we really want we can also add a bugfix branch but as neither me, nor you use this in a high scaled setup where you can't edit the configs if something breaks I guess we can use it as it is. Docker itself handles the container updates and we make sure that it just works ^^

**Comment by bddenhartog** [comment]
Docker doesn't handle the container updates itself actually, unless the user specifically pulls the image again they won't get a new iteration of whatever tag they have pulled down. 

Because the image is built automatically from this repository and I have specified that `latest` should always be built from the `master` branch, we don't have to worry about what `latest` correlates to as that's already decided for us through the defined development workflow.

The thing is, while there isn't currently much in the project besides the image, there are plans for future development, integration of ice and a webui, automatic proxy provisioning, etc. I think it's important that we snapshot the growth of the project somehow, so users can easily grab the image from a specific point in time, and tags (on both the git repo and the built image) are the traditional way to do that.

If this project was *only* focused on providing 1:1 parity with the options available to murmur, then I guess it would make sense to follow the mumble project's versioning, but because there are things we do/may do that are *outside* of the scope of simply running murmur, I think it makes sense to stick with our own versions. As long as releases have good visibility, and specify the versions of the dependencies used (e.g. `v1.2.3 of this repo uses v.1.2.17 of murmur and v3.4.5 of nginx`) I don't think people will be too confused.

There's an interesting discussion regarding updates to versions after dependency updates [here](https://github.com/mojombo/semver/issues/148), and I think this kind of solidified the decision for me -- even though this project is really just a "wrapper" around murmur *at the moment*, that's not what it will be in the future and it makes sense to consider murmur (and any other external projects) as just that -- external projects, or dependencies.

As always, thanks for the chat and ideas :)

**Comment by bddenhartog** [comment]
The stance on versioning changed with #66. `containerly/murmur` tags now match release versions from the `mumble-voip/mumble` project.
